repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: ["--fix", "--preview"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        entry: python -m mypy
        additional_dependencies:
          - types-requests
          - pydantic
          - pydantic-settings
          - sqlalchemy
          - fastapi
          - alembic
          - pytest-asyncio
  
        args: ["--pretty", "--show-error-codes"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
        name: Bandit security check
        args: ["-r", "app", "-c", "bandit.yml"]
        pass_filenames: false

  - repo: local
    hooks:
      - id: run-pytest
        name: pytest
        entry: venv\\Scripts\\python.exe -m pytest tests/ app/
        language: system
        args: ["-v"]
        pass_filenames: false
        types: [python]
