sonar.projectKey=fastapi-started
sonar.projectName=FastAPI Started

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.10

sonar.exclusions=\
**/venv/**,\
**/.pytest_cache/**,\
**/.mypy_cache/**,\
**/__pycache__/**,\
**/uploads/**,\
**/static/**